spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: bestuser
    password: bestuser
  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
